#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# ============================================================
# RMA Environment Discovery Script
# Generated by Resilience Migration Advisor (RMA)
# Scans all enabled AWS regions for resources and dependencies
# Produces: resources-inventory.csv, resource-dependencies.csv
#
# PAGINATION NOTE:
# AWS CLI v2 auto-paginates all list/describe calls by default,
# returning the full result set across multiple API pages.
# AWS CLI v1 also auto-paginates most commands.
# This script relies on that default behavior. If you are using
# a custom AWS CLI configuration with max_items or have disabled
# auto-pagination, results may be incomplete for large environments.
# Verify: aws configure get cli_pager  (should be empty or "less")
# Ref: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html
# ============================================================
set -o pipefail

# --- Configuration ---
MAX_RETRIES=3
INVENTORY_FILE="resources-inventory.csv"
DEPENDENCY_FILE="resource-dependencies.csv"
SCRIPT_START=$(date +%s)
TOTAL_RESOURCES=0
TOTAL_DEPENDENCIES=0
REGIONS_SCANNED=0
COLLECTION_FAILURES=""

# --- Color output helpers ---
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
CYAN="\033[0;36m"
NC="\033[0m"

log_info()  { echo -e "${CYAN}[INFO]${NC}  $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

track_failure() {
  local resource_type="$1"
  local region="$2"
  local reason="$3"
  COLLECTION_FAILURES="${COLLECTION_FAILURES}${resource_type} in ${region}: ${reason}\n"
}

# --- Retry with exponential backoff ---
aws_retry() {
  local attempt=0
  local output=""
  local exit_code=0
  while [ $attempt -lt $MAX_RETRIES ]; do
    output=$(eval "$@" 2>&1)
    exit_code=$?
    if [ $exit_code -eq 0 ]; then
      echo "$output"
      return 0
    fi
    if echo "$output" | grep -qi "AccessDenied\|UnauthorizedAccess\|AuthorizationError"; then
      echo "$output" >&2
      return 2
    fi
    if echo "$output" | grep -qi "InvalidClientTokenId\|UnrecognizedClientException\|not available\|Could not connect"; then
      echo "$output" >&2
      return 3
    fi
    attempt=$((attempt + 1))
    if [ $attempt -lt $MAX_RETRIES ]; then
      local wait_time=$((1 << attempt))
      log_warn "Retry $attempt/$MAX_RETRIES in ${wait_time}s..." >&2
      sleep $wait_time
    fi
  done
  echo "$output" >&2
  return 1
}

sanitize_csv() {
  local val="$1"
  # Prefix dangerous leading characters with single quote to neutralize formula execution
  case "$val" in
    =*|+*|-*|@*) val="'$val" ;;
  esac
  # Escape embedded double quotes by doubling them (RFC 4180)
  val="${val//\"/\"\"}"
  # Wrap in double quotes to safely preserve commas and special characters
  printf '"%s"' "$val"
}

add_inventory() {
  local rtype rid rname region service account details
  rtype="$(sanitize_csv "$1")"
  rid="$(sanitize_csv "$2")"
  rname="$(sanitize_csv "$3")"
  region="$(sanitize_csv "$4")"
  service="$(sanitize_csv "$5")"
  account="$(sanitize_csv "$6")"
  details="$(sanitize_csv "$7")"
  printf '%s,%s,%s,%s,%s,%s,%s\n' "$rtype" "$rid" "$rname" "$region" "$service" "$account" "$details" >> "$INVENTORY_FILE"
  TOTAL_RESOURCES=$((TOTAL_RESOURCES + 1))
}

add_dependency() {
  local src dep_type target region
  src="$(sanitize_csv "$1")"
  dep_type="$(sanitize_csv "$2")"
  target="$(sanitize_csv "$3")"
  region="$(sanitize_csv "$4")"
  printf '%s,%s,%s,%s\n' "$src" "$dep_type" "$target" "$region" >> "$DEPENDENCY_FILE"
  TOTAL_DEPENDENCIES=$((TOTAL_DEPENDENCIES + 1))
}

# ============================================================
# DEPENDENCY CHECKS
# ============================================================
log_info "RMA Environment Discovery Script starting..."

# Check AWS CLI
if ! command -v aws &>/dev/null; then
  log_error "AWS CLI is not installed."
  echo "Please install the AWS CLI:"
  echo "  https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
  echo "  pip install awscli"
  echo "  brew install awscli"
  exit 1
fi
log_ok "AWS CLI found: $(aws --version 2>&1 | head -1)"

# Check credentials
CALLER_IDENTITY=$(aws sts get-caller-identity --output text 2>&1)
if [ $? -ne 0 ]; then
  log_error "AWS credentials are not configured or are invalid."
  echo "Please configure credentials:"
  echo "  aws configure"
  echo "  export AWS_PROFILE=your-profile"
  echo "  export AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=..."
  exit 1
fi
ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
log_ok "Authenticated as Account: $ACCOUNT_ID"

# ============================================================
# INITIALIZE CSV FILES
# ============================================================
echo "ResourceType,ResourceId,ResourceName,Region,Service,AccountId,AdditionalDetails" > "$INVENTORY_FILE"
chmod 600 "$INVENTORY_FILE"
echo "SourceResource,DependencyType,TargetResource,Region" > "$DEPENDENCY_FILE"
chmod 600 "$DEPENDENCY_FILE"

# ============================================================
# REGION DETECTION
# ============================================================
log_info "Detecting enabled regions..."
REGIONS=$(aws ec2 describe-regions --query "Regions[].RegionName" --output text)
if [ -z "$REGIONS" ]; then
  log_error "Could not detect AWS regions."
  exit 1
fi
REGION_COUNT=$(echo "$REGIONS" | wc -w | tr -d " ")
log_ok "Found $REGION_COUNT enabled regions"

# ============================================================
# ACCOUNT-LEVEL INFO (global, collected once)
# ============================================================
log_info "Collecting account-level information..."
add_inventory "Account" "$ACCOUNT_ID" "AWSAccount" "global" "STS" "$ACCOUNT_ID" "RegionCount=$REGION_COUNT"

# Organization membership
ORG_ID=$(aws_retry "aws organizations describe-organization --query \"Organization.Id\" --output text" 2>/dev/null)
if [ $? -eq 0 ] && [ -n "$ORG_ID" ] && [ "$ORG_ID" != "None" ]; then
  add_inventory "Organization" "$ORG_ID" "AWSOrganization" "global" "Organizations" "$ACCOUNT_ID" ""
fi

# Cross-account roles
log_info "Checking for cross-account IAM roles..."
ROLES=$(aws_retry "aws iam list-roles --query \"Roles[].{RoleName:RoleName,Arn:Arn}\" --output text" 2>/dev/null)
if [ $? -eq 0 ] && [ -n "$ROLES" ]; then
  echo "$ROLES" | while IFS=$'\t' read -r arn rname; do
    if [ -n "$arn" ]; then
      TRUST=$(aws_retry "aws iam get-role --role-name \"$rname\" --query \"Role.AssumeRolePolicyDocument\" --output text" 2>/dev/null)
      if echo "$TRUST" | grep -q "arn:aws:iam::" 2>/dev/null; then
        TRUSTED_ACCOUNTS=$(echo "$TRUST" | grep -o "arn:aws:iam::[0-9]*" | grep -v "$ACCOUNT_ID" | sort -u)
        if [ -n "$TRUSTED_ACCOUNTS" ]; then
          add_inventory "CrossAccountRole" "$arn" "$rname" "global" "IAM" "$ACCOUNT_ID" "TrustedAccounts=$(echo "$TRUSTED_ACCOUNTS" | tr '\n' ';')"
        fi
      fi
    fi
  done
fi

# ============================================================
# GLOBAL SERVICES (collected once, not per-region)
# ============================================================

# --- S3 Buckets (global) ---
log_info "Collecting S3 buckets (global)..."
S3_BUCKETS=$(aws_retry "aws s3api list-buckets --query \"Buckets[].Name\" --output text" 2>/dev/null)
S3_RC=$?
if [ $S3_RC -eq 0 ] && [ -n "$S3_BUCKETS" ] && [ "$S3_BUCKETS" != "None" ]; then
  S3_COUNT=0
  # Intentional word splitting: S3_BUCKETS is a space-delimited list from AWS CLI
  for bucket in $S3_BUCKETS; do
    BUCKET_REGION=$(aws_retry "aws s3api get-bucket-location --bucket \"$bucket\" --query \"LocationConstraint\" --output text" 2>/dev/null)
    if [ "$BUCKET_REGION" = "None" ] || [ -z "$BUCKET_REGION" ]; then BUCKET_REGION="us-east-1"; fi
    ENCRYPTION=$(aws_retry "aws s3api get-bucket-encryption --bucket \"$bucket\" --query \"ServerSideEncryptionConfiguration.Rules[0].ApplyServerSideEncryptionByDefault.SSEAlgorithm\" --output text" 2>/dev/null || echo "None")
    # S3 bucket size via CloudWatch (read-only, no object listing)
    CW_START=$(date -u -v-2d +%Y-%m-%dT%H:%M:%S 2>/dev/null || date -u -d '2 days ago' +%Y-%m-%dT%H:%M:%S)
    CW_END=$(date -u +%Y-%m-%dT%H:%M:%S)
    BUCKET_SIZE_BYTES=$(aws_retry "aws cloudwatch get-metric-statistics --namespace AWS/S3 --metric-name BucketSizeBytes --dimensions Name=BucketName,Value=\"$bucket\" Name=StorageType,Value=StandardStorage --start-time \"$CW_START\" --end-time \"$CW_END\" --period 86400 --statistics Average --query \"Datapoints[0].Average\" --output text" 2>/dev/null || echo "N/A")
    if [ "$BUCKET_SIZE_BYTES" = "None" ] || [ -z "$BUCKET_SIZE_BYTES" ]; then BUCKET_SIZE_BYTES="N/A"; fi
    add_inventory "S3Bucket" "$bucket" "$bucket" "$BUCKET_REGION" "S3" "$ACCOUNT_ID" "Encryption=$ENCRYPTION,SizeBytes=$BUCKET_SIZE_BYTES"
    S3_COUNT=$((S3_COUNT + 1))
    # S3 replication
    REPL_DEST=$(aws_retry "aws s3api get-bucket-replication --bucket \"$bucket\" --query \"ReplicationConfiguration.Rules[].Destination.Bucket\" --output text" 2>/dev/null)
    if [ $? -eq 0 ] && [ -n "$REPL_DEST" ] && [ "$REPL_DEST" != "None" ]; then
      # Intentional word splitting: REPL_DEST is a space-delimited list from AWS CLI
      for dest in $REPL_DEST; do
        add_dependency "$bucket" "S3-ReplicationDestination" "$dest" "$BUCKET_REGION"
      done
    fi
    # S3 lifecycle
    LC_STATUS=$(aws_retry "aws s3api get-bucket-lifecycle-configuration --bucket \"$bucket\" --query \"length(Rules)\" --output text" 2>/dev/null || echo "0")
    if [ "$LC_STATUS" != "0" ] && [ "$LC_STATUS" != "None" ] && [ -n "$LC_STATUS" ]; then
      add_inventory "S3Lifecycle" "${bucket}-lifecycle" "$bucket" "$BUCKET_REGION" "S3" "$ACCOUNT_ID" "RuleCount=$LC_STATUS"
    fi
  done
  log_ok "Found $S3_COUNT S3 buckets"
elif [ $S3_RC -eq 2 ]; then
  log_warn "Permission denied for S3 bucket listing"
  track_failure "S3Buckets" "global" "Permission denied"
elif [ $S3_RC -eq 3 ]; then
  log_warn "S3 service not available"
  track_failure "S3Buckets" "global" "Service unavailable"
fi

# --- CloudFront Distributions (global) ---
log_info "Collecting CloudFront distributions (global)..."
CF_OUTPUT=$(aws_retry "aws cloudfront list-distributions --query \"DistributionList.Items[].{Id:Id,Domain:DomainName,Origins:Origins.Items[].DomainName}\" --output text" 2>/dev/null)
CF_RC=$?
if [ $CF_RC -eq 0 ] && [ -n "$CF_OUTPUT" ] && [ "$CF_OUTPUT" != "None" ]; then
  CF_IDS=$(aws_retry "aws cloudfront list-distributions --query \"DistributionList.Items[].Id\" --output text" 2>/dev/null)
  CF_COUNT=0
  # Intentional word splitting: CF_IDS is a space-delimited list from AWS CLI
  for cfid in $CF_IDS; do
    CF_DOMAIN=$(aws_retry "aws cloudfront get-distribution --id \"$cfid\" --query \"Distribution.DomainName\" --output text" 2>/dev/null)
    CF_ORIGINS=$(aws_retry "aws cloudfront get-distribution --id \"$cfid\" --query \"Distribution.DistributionConfig.Origins.Items[].DomainName\" --output text" 2>/dev/null)
    add_inventory "CloudFrontDistribution" "$cfid" "$CF_DOMAIN" "global" "CloudFront" "$ACCOUNT_ID" "Origins=$(echo "$CF_ORIGINS" | tr '\t' ';')"
    CF_COUNT=$((CF_COUNT + 1))
    # CloudFront -> Origin dependencies
    # Intentional word splitting: CF_ORIGINS is a space-delimited list from AWS CLI
    for origin in $CF_ORIGINS; do
      add_dependency "$cfid" "CloudFront-Origin" "$origin" "global"
    done
  done
  log_ok "Found $CF_COUNT CloudFront distributions"
elif [ $CF_RC -eq 2 ]; then
  log_warn "Permission denied for CloudFront"
  track_failure "CloudFront" "global" "Permission denied"
elif [ $CF_RC -eq 3 ]; then
  log_warn "CloudFront service not available"
  track_failure "CloudFront" "global" "Service unavailable"
fi

# --- Route 53 (global) ---
log_info "Collecting Route 53 hosted zones (global)..."
R53_ZONES=$(aws_retry "aws route53 list-hosted-zones --query \"HostedZones[].{Id:Id,Name:Name}\" --output text" 2>/dev/null)
R53_RC=$?
if [ $R53_RC -eq 0 ] && [ -n "$R53_ZONES" ] && [ "$R53_ZONES" != "None" ]; then
  R53_COUNT=0
  echo "$R53_ZONES" | while IFS=$'\t' read -r zid zname; do
    if [ -n "$zid" ]; then
      ZONE_ID=$(echo "$zid" | sed "s|/hostedzone/||")
      add_inventory "Route53HostedZone" "$ZONE_ID" "$zname" "global" "Route53" "$ACCOUNT_ID" ""
      R53_COUNT=$((R53_COUNT + 1))
      # Records for this zone
      RECORDS=$(aws_retry "aws route53 list-resource-record-sets --hosted-zone-id \"$zid\" --query \"ResourceRecordSets[].{Name:Name,Type:Type,Alias:AliasTarget.DNSName}\" --output text" 2>/dev/null)
      if [ $? -eq 0 ] && [ -n "$RECORDS" ]; then
        echo "$RECORDS" | while IFS=$'\t' read -r alias rname rtype; do
          if [ -n "$rname" ]; then
            add_inventory "Route53Record" "${ZONE_ID}:${rname}:${rtype}" "$rname" "global" "Route53" "$ACCOUNT_ID" "Type=$rtype"
            # Route53 -> LB/CloudFront alias dependencies
            if [ -n "$alias" ] && [ "$alias" != "None" ]; then
              if echo "$alias" | grep -qi "elb\|alb\|nlb\|amazonaw"; then
                add_dependency "${ZONE_ID}:${rname}" "Route53-LoadBalancer" "$alias" "global"
              elif echo "$alias" | grep -qi "cloudfront"; then
                add_dependency "${ZONE_ID}:${rname}" "Route53-CloudFront" "$alias" "global"
              fi
            fi
          fi
        done
      fi
    fi
  done
  log_ok "Found Route 53 hosted zones"
elif [ $R53_RC -eq 2 ]; then
  log_warn "Permission denied for Route 53"
  track_failure "Route53" "global" "Permission denied"
elif [ $R53_RC -eq 3 ]; then
  log_warn "Route 53 service not available"
  track_failure "Route53" "global" "Service unavailable"
fi

# Route 53 Health Checks
log_info "Collecting Route 53 health checks (global)..."
R53_HC=$(aws_retry "aws route53 list-health-checks --query \"HealthChecks[].{Id:Id,Config:HealthCheckConfig.FullyQualifiedDomainName}\" --output text" 2>/dev/null)
if [ $? -eq 0 ] && [ -n "$R53_HC" ] && [ "$R53_HC" != "None" ]; then
  echo "$R53_HC" | while IFS=$'\t' read -r hcfqdn hcid; do
    if [ -n "$hcid" ]; then
      add_inventory "Route53HealthCheck" "$hcid" "$hcfqdn" "global" "Route53" "$ACCOUNT_ID" ""
    fi
  done
fi

# ============================================================
# PER-REGION RESOURCE COLLECTION
# ============================================================
# Intentional word splitting: REGIONS is a space-delimited list from AWS CLI
for REGION in $REGIONS; do
  REGION_START=$(date +%s)
  log_info "\n========== Region: $REGION =========="

  # --- Network Topology ---

  # VPCs
  log_info "[$REGION] Collecting VPCs..."
  VPCS=$(aws_retry "aws ec2 describe-vpcs --region $REGION --query \"Vpcs[].{Id:VpcId,Cidr:CidrBlock,Name:Tags[?Key==\\\"Name\\\"].Value|[0]}\" --output text" 2>/dev/null)
  VPC_RC=$?
  if [ $VPC_RC -eq 0 ] && [ -n "$VPCS" ] && [ "$VPCS" != "None" ]; then
    VPC_COUNT=0
    echo "$VPCS" | while IFS=$'\t' read -r vcidr vid vname; do
      if [ -n "$vid" ]; then
        add_inventory "VPC" "$vid" "${vname:-$vid}" "$REGION" "EC2" "$ACCOUNT_ID" "CIDR=$vcidr"
        VPC_COUNT=$((VPC_COUNT + 1))
      fi
    done
    log_ok "[$REGION] Found VPCs"
  elif [ $VPC_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for VPCs"
    track_failure "VPC" "$REGION" "Permission denied"
  elif [ $VPC_RC -eq 3 ]; then
    log_warn "[$REGION] EC2 service not available"
    track_failure "VPC" "$REGION" "Service unavailable"
  fi

  # Subnets
  log_info "[$REGION] Collecting Subnets..."
  SUBNETS=$(aws_retry "aws ec2 describe-subnets --region $REGION --query \"Subnets[].{Id:SubnetId,VpcId:VpcId,AZ:AvailabilityZone,Cidr:CidrBlock,Name:Tags[?Key==\\\"Name\\\"].Value|[0]}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$SUBNETS" ] && [ "$SUBNETS" != "None" ]; then
    echo "$SUBNETS" | while IFS=$'\t' read -r saz scidr sid svpc sname; do
      if [ -n "$sid" ]; then
        add_inventory "Subnet" "$sid" "${sname:-$sid}" "$REGION" "EC2" "$ACCOUNT_ID" "VPC=$svpc;AZ=$saz;CIDR=$scidr"
        add_dependency "$svpc" "VPC-Subnet" "$sid" "$REGION"
      fi
    done
  fi

  # Route Tables
  log_info "[$REGION] Collecting Route Tables..."
  RTS=$(aws_retry "aws ec2 describe-route-tables --region $REGION --query \"RouteTables[].{Id:RouteTableId,VpcId:VpcId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$RTS" ] && [ "$RTS" != "None" ]; then
    echo "$RTS" | while IFS=$'\t' read -r rtid rtvpc; do
      if [ -n "$rtid" ]; then
        add_inventory "RouteTable" "$rtid" "$rtid" "$REGION" "EC2" "$ACCOUNT_ID" "VPC=$rtvpc"
      fi
    done
  fi

  # Internet Gateways
  log_info "[$REGION] Collecting Internet Gateways..."
  IGWS=$(aws_retry "aws ec2 describe-internet-gateways --region $REGION --query \"InternetGateways[].{Id:InternetGatewayId,Attachments:Attachments[].VpcId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$IGWS" ] && [ "$IGWS" != "None" ]; then
    echo "$IGWS" | while IFS=$'\t' read -r igwatt igwid; do
      if [ -n "$igwid" ]; then
        add_inventory "InternetGateway" "$igwid" "$igwid" "$REGION" "EC2" "$ACCOUNT_ID" "VPC=$igwatt"
      fi
    done
  fi

  # NAT Gateways
  log_info "[$REGION] Collecting NAT Gateways..."
  NATGWS=$(aws_retry "aws ec2 describe-nat-gateways --region $REGION --query \"NatGateways[?State==\\\"available\\\"].{Id:NatGatewayId,SubnetId:SubnetId,VpcId:VpcId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$NATGWS" ] && [ "$NATGWS" != "None" ]; then
    echo "$NATGWS" | while IFS=$'\t' read -r natid natsub natvpc; do
      if [ -n "$natid" ]; then
        add_inventory "NATGateway" "$natid" "$natid" "$REGION" "EC2" "$ACCOUNT_ID" "VPC=$natvpc;Subnet=$natsub"
      fi
    done
  fi

  # Transit Gateways
  log_info "[$REGION] Collecting Transit Gateways..."
  TGWS=$(aws_retry "aws ec2 describe-transit-gateways --region $REGION --query \"TransitGateways[].{Id:TransitGatewayId,State:State}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$TGWS" ] && [ "$TGWS" != "None" ]; then
    echo "$TGWS" | while IFS=$'\t' read -r tgwid tgwstate; do
      if [ -n "$tgwid" ]; then
        add_inventory "TransitGateway" "$tgwid" "$tgwid" "$REGION" "EC2" "$ACCOUNT_ID" "State=$tgwstate"
        # TGW Attachments
        TGW_ATT=$(aws_retry "aws ec2 describe-transit-gateway-attachments --region $REGION --filters Name=transit-gateway-id,Values=$tgwid --query \"TransitGatewayAttachments[].{Id:TransitGatewayAttachmentId,ResId:ResourceId,ResType:ResourceType}\" --output text" 2>/dev/null)
        if [ $? -eq 0 ] && [ -n "$TGW_ATT" ] && [ "$TGW_ATT" != "None" ]; then
          echo "$TGW_ATT" | while IFS=$'\t' read -r attid attres atttype; do
            if [ -n "$attid" ]; then
              add_inventory "TransitGatewayAttachment" "$attid" "$attid" "$REGION" "EC2" "$ACCOUNT_ID" "TGW=$tgwid;Resource=$attres;Type=$atttype"
              add_dependency "$tgwid" "TGW-VPCAttachment" "$attres" "$REGION"
            fi
          done
        fi
        # TGW Route Tables
        TGW_RT=$(aws_retry "aws ec2 describe-transit-gateway-route-tables --region $REGION --filters Name=transit-gateway-id,Values=$tgwid --query \"TransitGatewayRouteTables[].TransitGatewayRouteTableId\" --output text" 2>/dev/null)
        if [ $? -eq 0 ] && [ -n "$TGW_RT" ] && [ "$TGW_RT" != "None" ]; then
          # Intentional word splitting: TGW_RT is a space-delimited list from AWS CLI
          for tgwrt in $TGW_RT; do
            add_inventory "TransitGatewayRouteTable" "$tgwrt" "$tgwrt" "$REGION" "EC2" "$ACCOUNT_ID" "TGW=$tgwid"
          done
        fi
      fi
    done
  fi

  # VPC Peering
  log_info "[$REGION] Collecting VPC Peering connections..."
  PEERS=$(aws_retry "aws ec2 describe-vpc-peering-connections --region $REGION --query \"VpcPeeringConnections[].{Id:VpcPeeringConnectionId,Req:RequesterVpcInfo.VpcId,Acc:AccepterVpcInfo.VpcId,Status:Status.Code}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$PEERS" ] && [ "$PEERS" != "None" ]; then
    echo "$PEERS" | while IFS=$'\t' read -r pacc pid preq pstatus; do
      if [ -n "$pid" ]; then
        add_inventory "VPCPeering" "$pid" "$pid" "$REGION" "EC2" "$ACCOUNT_ID" "Requester=$preq;Accepter=$pacc;Status=$pstatus"
      fi
    done
  fi

  # VPC Endpoints (PrivateLink + Gateway)
  log_info "[$REGION] Collecting VPC Endpoints..."
  VPCE=$(aws_retry "aws ec2 describe-vpc-endpoints --region $REGION --query \"VpcEndpoints[].{Id:VpcEndpointId,VpcId:VpcId,Service:ServiceName,Type:VpcEndpointType,Subnets:SubnetIds,SGs:Groups[].GroupId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$VPCE" ] && [ "$VPCE" != "None" ]; then
    VPCE_IDS=$(aws_retry "aws ec2 describe-vpc-endpoints --region $REGION --query \"VpcEndpoints[].VpcEndpointId\" --output text" 2>/dev/null)
    # Intentional word splitting: VPCE_IDS is a space-delimited list from AWS CLI
    for veid in $VPCE_IDS; do
      VE_SVC=$(aws_retry "aws ec2 describe-vpc-endpoints --region $REGION --vpc-endpoint-ids $veid --query \"VpcEndpoints[0].ServiceName\" --output text" 2>/dev/null)
      VE_VPC=$(aws_retry "aws ec2 describe-vpc-endpoints --region $REGION --vpc-endpoint-ids $veid --query \"VpcEndpoints[0].VpcId\" --output text" 2>/dev/null)
      VE_TYPE=$(aws_retry "aws ec2 describe-vpc-endpoints --region $REGION --vpc-endpoint-ids $veid --query \"VpcEndpoints[0].VpcEndpointType\" --output text" 2>/dev/null)
      VE_SUBNETS=$(aws_retry "aws ec2 describe-vpc-endpoints --region $REGION --vpc-endpoint-ids $veid --query \"VpcEndpoints[0].SubnetIds\" --output text" 2>/dev/null)
      VE_SGS=$(aws_retry "aws ec2 describe-vpc-endpoints --region $REGION --vpc-endpoint-ids $veid --query \"VpcEndpoints[0].Groups[].GroupId\" --output text" 2>/dev/null)
      add_inventory "VPCEndpoint" "$veid" "$VE_SVC" "$REGION" "EC2" "$ACCOUNT_ID" "VPC=$VE_VPC;Type=$VE_TYPE"
      add_dependency "$veid" "VPCEndpoint-Service" "$VE_SVC" "$REGION"
      if [ -n "$VE_SUBNETS" ] && [ "$VE_SUBNETS" != "None" ]; then
        # Intentional word splitting: VE_SUBNETS is a space-delimited list from AWS CLI
        for vesub in $VE_SUBNETS; do
          add_dependency "$veid" "VPCEndpoint-Subnet" "$vesub" "$REGION"
        done
      fi
      if [ -n "$VE_SGS" ] && [ "$VE_SGS" != "None" ]; then
        # Intentional word splitting: VE_SGS is a space-delimited list from AWS CLI
        for vesg in $VE_SGS; do
          add_dependency "$veid" "VPCEndpoint-SecurityGroup" "$vesg" "$REGION"
        done
      fi
    done
  fi

  # Elastic IPs
  log_info "[$REGION] Collecting Elastic IPs..."
  EIPS=$(aws_retry "aws ec2 describe-addresses --region $REGION --query \"Addresses[].{AllocationId:AllocationId,PublicIp:PublicIp,InstanceId:InstanceId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$EIPS" ] && [ "$EIPS" != "None" ]; then
    echo "$EIPS" | while IFS=$'\t' read -r eipalloc eipinst eippub; do
      if [ -n "$eipalloc" ]; then
        add_inventory "ElasticIP" "$eipalloc" "$eippub" "$REGION" "EC2" "$ACCOUNT_ID" "Instance=$eipinst"
      fi
    done
  fi

  # ENIs
  log_info "[$REGION] Collecting ENIs..."
  ENIS=$(aws_retry "aws ec2 describe-network-interfaces --region $REGION --query \"NetworkInterfaces[].{Id:NetworkInterfaceId,SubnetId:SubnetId,VpcId:VpcId,Type:InterfaceType}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$ENIS" ] && [ "$ENIS" != "None" ]; then
    echo "$ENIS" | while IFS=$'\t' read -r eniid enisub enitype enivpc; do
      if [ -n "$eniid" ]; then
        add_inventory "ENI" "$eniid" "$eniid" "$REGION" "EC2" "$ACCOUNT_ID" "VPC=$enivpc;Subnet=$enisub;Type=$enitype"
      fi
    done
  fi

  # Site-to-Site VPN
  log_info "[$REGION] Collecting VPN connections..."
  VPNS=$(aws_retry "aws ec2 describe-vpn-connections --region $REGION --query \"VpnConnections[].{Id:VpnConnectionId,State:State,CGWID:CustomerGatewayId,VGWID:VpnGatewayId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$VPNS" ] && [ "$VPNS" != "None" ]; then
    echo "$VPNS" | while IFS=$'\t' read -r vpncgw vpnid vpnstate vpnvgw; do
      if [ -n "$vpnid" ]; then
        add_inventory "VPNConnection" "$vpnid" "$vpnid" "$REGION" "EC2" "$ACCOUNT_ID" "State=$vpnstate;CGW=$vpncgw;VGW=$vpnvgw"
      fi
    done
  fi

  # Customer Gateways
  CGWS=$(aws_retry "aws ec2 describe-customer-gateways --region $REGION --query \"CustomerGateways[].{Id:CustomerGatewayId,State:State,IP:IpAddress}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$CGWS" ] && [ "$CGWS" != "None" ]; then
    echo "$CGWS" | while IFS=$'\t' read -r cgwid cgwip cgwstate; do
      if [ -n "$cgwid" ]; then
        add_inventory "CustomerGateway" "$cgwid" "$cgwid" "$REGION" "EC2" "$ACCOUNT_ID" "State=$cgwstate;IP=$cgwip"
      fi
    done
  fi

  # Virtual Private Gateways
  VGWS=$(aws_retry "aws ec2 describe-vpn-gateways --region $REGION --query \"VpnGateways[].{Id:VpnGatewayId,State:State}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$VGWS" ] && [ "$VGWS" != "None" ]; then
    echo "$VGWS" | while IFS=$'\t' read -r vgwid vgwstate; do
      if [ -n "$vgwid" ]; then
        add_inventory "VirtualPrivateGateway" "$vgwid" "$vgwid" "$REGION" "EC2" "$ACCOUNT_ID" "State=$vgwstate"
      fi
    done
  fi

  # Direct Connect
  log_info "[$REGION] Collecting Direct Connect connections..."
  DX=$(aws_retry "aws directconnect describe-connections --region $REGION --query \"connections[].{Id:connectionId,Name:connectionName,State:connectionState}\" --output text" 2>/dev/null)
  DX_RC=$?
  if [ $DX_RC -eq 0 ] && [ -n "$DX" ] && [ "$DX" != "None" ]; then
    echo "$DX" | while IFS=$'\t' read -r dxid dxname dxstate; do
      if [ -n "$dxid" ]; then
        add_inventory "DirectConnect" "$dxid" "$dxname" "$REGION" "DirectConnect" "$ACCOUNT_ID" "State=$dxstate"
      fi
    done
  elif [ $DX_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for Direct Connect"
    track_failure "DirectConnect" "$REGION" "Permission denied"
  elif [ $DX_RC -eq 3 ]; then
    log_warn "[$REGION] Direct Connect not available"
    track_failure "DirectConnect" "$REGION" "Service unavailable"
  fi

  # --- Network Security ---

  # Security Groups
  log_info "[$REGION] Collecting Security Groups..."
  SGS=$(aws_retry "aws ec2 describe-security-groups --region $REGION --query \"SecurityGroups[].{Id:GroupId,Name:GroupName,VpcId:VpcId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$SGS" ] && [ "$SGS" != "None" ]; then
    echo "$SGS" | while IFS=$'\t' read -r sgid sgname sgvpc; do
      if [ -n "$sgid" ]; then
        add_inventory "SecurityGroup" "$sgid" "$sgname" "$REGION" "EC2" "$ACCOUNT_ID" "VPC=$sgvpc"
      fi
    done
  fi

  # NACLs
  log_info "[$REGION] Collecting NACLs..."
  NACLS=$(aws_retry "aws ec2 describe-network-acls --region $REGION --query \"NetworkAcls[].{Id:NetworkAclId,VpcId:VpcId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$NACLS" ] && [ "$NACLS" != "None" ]; then
    echo "$NACLS" | while IFS=$'\t' read -r naclid naclvpc; do
      if [ -n "$naclid" ]; then
        add_inventory "NetworkACL" "$naclid" "$naclid" "$REGION" "EC2" "$ACCOUNT_ID" "VPC=$naclvpc"
      fi
    done
  fi

  # Network Firewall
  log_info "[$REGION] Collecting Network Firewall..."
  NFW=$(aws_retry "aws network-firewall list-firewalls --region $REGION --query \"Firewalls[].{Name:FirewallName,Arn:FirewallArn}\" --output text" 2>/dev/null)
  NFW_RC=$?
  if [ $NFW_RC -eq 0 ] && [ -n "$NFW" ] && [ "$NFW" != "None" ]; then
    echo "$NFW" | while IFS=$'\t' read -r nfwarn nfwname; do
      if [ -n "$nfwarn" ]; then
        add_inventory "NetworkFirewall" "$nfwarn" "$nfwname" "$REGION" "NetworkFirewall" "$ACCOUNT_ID" ""
      fi
    done
  elif [ $NFW_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for Network Firewall"
    track_failure "NetworkFirewall" "$REGION" "Permission denied"
  elif [ $NFW_RC -eq 3 ]; then
    log_warn "[$REGION] Network Firewall not available"
    track_failure "NetworkFirewall" "$REGION" "Service unavailable"
  fi

  # WAF Web ACLs (regional)
  log_info "[$REGION] Collecting WAF Web ACLs..."
  WAF=$(aws_retry "aws wafv2 list-web-acls --region $REGION --scope REGIONAL --query \"WebACLs[].{Name:Name,Id:Id,ARN:ARN}\" --output text" 2>/dev/null)
  WAF_RC=$?
  if [ $WAF_RC -eq 0 ] && [ -n "$WAF" ] && [ "$WAF" != "None" ]; then
    echo "$WAF" | while IFS=$'\t' read -r wafarn wafid wafname; do
      if [ -n "$wafid" ]; then
        add_inventory "WAFWebACL" "$wafid" "$wafname" "$REGION" "WAF" "$ACCOUNT_ID" "ARN=$wafarn"
      fi
    done
  elif [ $WAF_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for WAFv2"
    track_failure "WAFWebACL" "$REGION" "Permission denied"
  elif [ $WAF_RC -eq 3 ]; then
    log_warn "[$REGION] WAFv2 not available"
    track_failure "WAFWebACL" "$REGION" "Service unavailable"
  fi

  # --- Compute ---

  # EC2 Instances
  log_info "[$REGION] Collecting EC2 instances..."
  EC2S=$(aws_retry "aws ec2 describe-instances --region $REGION --query \"Reservations[].Instances[].{Id:InstanceId,Type:InstanceType,State:State.Name,SubnetId:SubnetId,VpcId:VpcId,SGs:SecurityGroups[].GroupId,Name:Tags[?Key==\\\"Name\\\"].Value|[0]}\" --output json" 2>/dev/null)
  EC2_RC=$?
  if [ $EC2_RC -eq 0 ] && [ -n "$EC2S" ] && [ "$EC2S" != "[]" ]; then
    EC2_IDS=$(echo "$EC2S" | grep -o '"InstanceId": "[^"]*"' | sed 's/"InstanceId": "//;s/"//g')
    EC2_COUNT=0
    # Intentional word splitting: EC2_IDS is a space-delimited list from AWS CLI
    for iid in $EC2_IDS; do
      I_TYPE=$(echo "$EC2S" | awk -v id="$iid" 'BEGIN{RS="\\{";FS="\\n"} $0~id{for(i=1;i<=NF;i++){if($i~/InstanceType/){gsub(/.*: "|".*$/,"",$i);print $i;exit}}}')
      I_STATE=$(echo "$EC2S" | awk -v id="$iid" 'BEGIN{RS="\\{";FS="\\n"} $0~id{for(i=1;i<=NF;i++){if($i~/"State"/){gsub(/.*: "|".*$/,"",$i);print $i;exit}}}')
      I_SUBNET=$(aws_retry "aws ec2 describe-instances --region $REGION --instance-ids $iid --query \"Reservations[0].Instances[0].SubnetId\" --output text" 2>/dev/null)
      I_VPC=$(aws_retry "aws ec2 describe-instances --region $REGION --instance-ids $iid --query \"Reservations[0].Instances[0].VpcId\" --output text" 2>/dev/null)
      I_NAME=$(aws_retry "aws ec2 describe-instances --region $REGION --instance-ids $iid --query \"Reservations[0].Instances[0].Tags[?Key==\\\"Name\\\"].Value|[0]\" --output text" 2>/dev/null)
      I_SGS=$(aws_retry "aws ec2 describe-instances --region $REGION --instance-ids $iid --query \"Reservations[0].Instances[0].SecurityGroups[].GroupId\" --output text" 2>/dev/null)
      I_VOLS=$(aws_retry "aws ec2 describe-instances --region $REGION --instance-ids $iid --query \"Reservations[0].Instances[0].BlockDeviceMappings[].Ebs.VolumeId\" --output text" 2>/dev/null)
      add_inventory "EC2Instance" "$iid" "${I_NAME:-$iid}" "$REGION" "EC2" "$ACCOUNT_ID" "Type=${I_TYPE:-unknown};State=${I_STATE:-unknown}"
      EC2_COUNT=$((EC2_COUNT + 1))
      # EC2 -> Subnet dependency
      if [ -n "$I_SUBNET" ] && [ "$I_SUBNET" != "None" ]; then
        add_dependency "$I_SUBNET" "Subnet-EC2" "$iid" "$REGION"
      fi
      # EC2 -> Security Group dependencies
      if [ -n "$I_SGS" ] && [ "$I_SGS" != "None" ]; then
        # Intentional word splitting: I_SGS is a space-delimited list from AWS CLI
        for sg in $I_SGS; do
          add_dependency "$iid" "EC2-SecurityGroup" "$sg" "$REGION"
        done
      fi
      # EC2 -> EBS Volume dependencies
      if [ -n "$I_VOLS" ] && [ "$I_VOLS" != "None" ]; then
        # Intentional word splitting: I_VOLS is a space-delimited list from AWS CLI
        for vol in $I_VOLS; do
          add_dependency "$iid" "EC2-EBSVolume" "$vol" "$REGION"
        done
      fi
    done
    log_ok "[$REGION] Found $EC2_COUNT EC2 instances"
  elif [ $EC2_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for EC2 instances"
    track_failure "EC2Instance" "$REGION" "Permission denied"
  elif [ $EC2_RC -eq 3 ]; then
    log_warn "[$REGION] EC2 service not available"
    track_failure "EC2Instance" "$REGION" "Service unavailable"
  fi

  # Auto Scaling Groups
  log_info "[$REGION] Collecting Auto Scaling Groups..."
  ASGS=$(aws_retry "aws autoscaling describe-auto-scaling-groups --region $REGION --query \"AutoScalingGroups[].{Name:AutoScalingGroupName,ARN:AutoScalingGroupARN,Min:MinSize,Max:MaxSize,Desired:DesiredCapacity}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$ASGS" ] && [ "$ASGS" != "None" ]; then
    echo "$ASGS" | while IFS=$'\t' read -r asgarn asgdes asgmax asgmin asgname; do
      if [ -n "$asgname" ]; then
        add_inventory "AutoScalingGroup" "$asgarn" "$asgname" "$REGION" "AutoScaling" "$ACCOUNT_ID" "Min=$asgmin;Max=$asgmax;Desired=$asgdes"
      fi
    done
  fi

  # Launch Templates
  log_info "[$REGION] Collecting Launch Templates..."
  LTS=$(aws_retry "aws ec2 describe-launch-templates --region $REGION --query \"LaunchTemplates[].{Id:LaunchTemplateId,Name:LaunchTemplateName}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$LTS" ] && [ "$LTS" != "None" ]; then
    echo "$LTS" | while IFS=$'\t' read -r ltid ltname; do
      if [ -n "$ltid" ]; then
        add_inventory "LaunchTemplate" "$ltid" "$ltname" "$REGION" "EC2" "$ACCOUNT_ID" ""
      fi
    done
  fi

  # Launch Configurations
  log_info "[$REGION] Collecting Launch Configurations..."
  LCS=$(aws_retry "aws autoscaling describe-launch-configurations --region $REGION --query \"LaunchConfigurations[].{Name:LaunchConfigurationName,ARN:LaunchConfigurationARN}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$LCS" ] && [ "$LCS" != "None" ]; then
    echo "$LCS" | while IFS=$'\t' read -r lcarn lcname; do
      if [ -n "$lcname" ]; then
        add_inventory "LaunchConfiguration" "$lcarn" "$lcname" "$REGION" "AutoScaling" "$ACCOUNT_ID" ""
      fi
    done
  fi

  # --- Load Balancing ---

  # ALBs and NLBs (ELBv2)
  log_info "[$REGION] Collecting Load Balancers (ALB/NLB)..."
  LBSV2=$(aws_retry "aws elbv2 describe-load-balancers --region $REGION --query \"LoadBalancers[].{ARN:LoadBalancerArn,Name:LoadBalancerName,Type:Type,VpcId:VpcId,Scheme:Scheme}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$LBSV2" ] && [ "$LBSV2" != "None" ]; then
    echo "$LBSV2" | while IFS=$'\t' read -r lbarn lbname lbscheme lbtype lbvpc; do
      if [ -n "$lbarn" ]; then
        add_inventory "LoadBalancer" "$lbarn" "$lbname" "$REGION" "ELBv2" "$ACCOUNT_ID" "Type=$lbtype;Scheme=$lbscheme;VPC=$lbvpc"
        # Listeners
        LISTENERS=$(aws_retry "aws elbv2 describe-listeners --load-balancer-arn \"$lbarn\" --region $REGION --query \"Listeners[].{ARN:ListenerArn,Port:Port,Protocol:Protocol}\" --output text" 2>/dev/null)
        if [ $? -eq 0 ] && [ -n "$LISTENERS" ] && [ "$LISTENERS" != "None" ]; then
          echo "$LISTENERS" | while IFS=$'\t' read -r listarn listport listproto; do
            if [ -n "$listarn" ]; then
              add_inventory "LBListener" "$listarn" "${lbname}:${listport}" "$REGION" "ELBv2" "$ACCOUNT_ID" "Port=$listport;Protocol=$listproto"
              add_dependency "$lbarn" "LB-Listener" "$listarn" "$REGION"
              # Target Groups for this listener
              TGS=$(aws_retry "aws elbv2 describe-listeners --listener-arns \"$listarn\" --region $REGION --query \"Listeners[0].DefaultActions[].TargetGroupArn\" --output text" 2>/dev/null)
              if [ $? -eq 0 ] && [ -n "$TGS" ] && [ "$TGS" != "None" ]; then
                # Intentional word splitting: TGS is a space-delimited list from AWS CLI
                for tgarn in $TGS; do
                  add_dependency "$listarn" "Listener-TargetGroup" "$tgarn" "$REGION"
                done
              fi
            fi
          done
        fi
      fi
    done
  fi

  # Target Groups
  log_info "[$REGION] Collecting Target Groups..."
  TGS_ALL=$(aws_retry "aws elbv2 describe-target-groups --region $REGION --query \"TargetGroups[].{ARN:TargetGroupArn,Name:TargetGroupName,VpcId:VpcId,Protocol:Protocol,Port:Port}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$TGS_ALL" ] && [ "$TGS_ALL" != "None" ]; then
    echo "$TGS_ALL" | while IFS=$'\t' read -r tgarn tgname tgport tgproto tgvpc; do
      if [ -n "$tgarn" ]; then
        add_inventory "TargetGroup" "$tgarn" "$tgname" "$REGION" "ELBv2" "$ACCOUNT_ID" "Protocol=$tgproto;Port=$tgport;VPC=$tgvpc"
        # Targets in this target group
        TARGETS=$(aws_retry "aws elbv2 describe-target-health --target-group-arn \"$tgarn\" --region $REGION --query \"TargetHealthDescriptions[].Target.Id\" --output text" 2>/dev/null)
        if [ $? -eq 0 ] && [ -n "$TARGETS" ] && [ "$TARGETS" != "None" ]; then
          # Intentional word splitting: TARGETS is a space-delimited list from AWS CLI
          for target in $TARGETS; do
            add_dependency "$tgarn" "TargetGroup-Target" "$target" "$REGION"
          done
        fi
      fi
    done
  fi

  # Classic Load Balancers
  log_info "[$REGION] Collecting Classic Load Balancers..."
  CLBS=$(aws_retry "aws elb describe-load-balancers --region $REGION --query \"LoadBalancerDescriptions[].{Name:LoadBalancerName,DNSName:DNSName,VPCId:VPCId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$CLBS" ] && [ "$CLBS" != "None" ]; then
    echo "$CLBS" | while IFS=$'\t' read -r clbdns clbname clbvpc; do
      if [ -n "$clbname" ]; then
        add_inventory "ClassicLoadBalancer" "$clbname" "$clbname" "$REGION" "ELB" "$ACCOUNT_ID" "DNS=$clbdns;VPC=$clbvpc"
      fi
    done
  fi

  # --- Storage ---

  # EBS Volumes
  log_info "[$REGION] Collecting EBS Volumes..."
  VOLS=$(aws_retry "aws ec2 describe-volumes --region $REGION --query \"Volumes[].{Id:VolumeId,Size:Size,State:State,Type:VolumeType,Encrypted:Encrypted,KmsKeyId:KmsKeyId}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$VOLS" ] && [ "$VOLS" != "None" ]; then
    echo "$VOLS" | while IFS=$'\t' read -r volenc volid volkms volsize volstate voltype; do
      if [ -n "$volid" ]; then
        add_inventory "EBSVolume" "$volid" "$volid" "$REGION" "EC2" "$ACCOUNT_ID" "Size=${volsize}GB;Type=$voltype;Encrypted=$volenc"
        # KMS dependency for encrypted volumes
        if [ "$volenc" = "True" ] && [ -n "$volkms" ] && [ "$volkms" != "None" ]; then
          add_dependency "$volid" "KMS-EncryptedResource" "$volkms" "$REGION"
        fi
      fi
    done
  fi

  # EBS Snapshots (owned by this account)
  log_info "[$REGION] Collecting EBS Snapshots..."
  SNAPS=$(aws_retry "aws ec2 describe-snapshots --region $REGION --owner-ids $ACCOUNT_ID --query \"Snapshots[].{Id:SnapshotId,VolumeId:VolumeId,Size:VolumeSize,State:State}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$SNAPS" ] && [ "$SNAPS" != "None" ]; then
    echo "$SNAPS" | while IFS=$'\t' read -r snapid snapsize snapstate snapvol; do
      if [ -n "$snapid" ]; then
        add_inventory "EBSSnapshot" "$snapid" "$snapid" "$REGION" "EC2" "$ACCOUNT_ID" "VolumeId=$snapvol;Size=${snapsize}GB"
      fi
    done
  fi

  # EFS File Systems
  log_info "[$REGION] Collecting EFS file systems..."
  EFS=$(aws_retry "aws efs describe-file-systems --region $REGION --query \"FileSystems[].{Id:FileSystemId,Name:Name,Encrypted:Encrypted,KmsKeyId:KmsKeyId}\" --output text" 2>/dev/null)
  EFS_RC=$?
  if [ $EFS_RC -eq 0 ] && [ -n "$EFS" ] && [ "$EFS" != "None" ]; then
    echo "$EFS" | while IFS=$'\t' read -r efsenc efsid efskms efsname; do
      if [ -n "$efsid" ]; then
        add_inventory "EFSFileSystem" "$efsid" "${efsname:-$efsid}" "$REGION" "EFS" "$ACCOUNT_ID" "Encrypted=$efsenc"
        if [ "$efsenc" = "True" ] && [ -n "$efskms" ] && [ "$efskms" != "None" ]; then
          add_dependency "$efsid" "KMS-EncryptedResource" "$efskms" "$REGION"
        fi
      fi
    done
  elif [ $EFS_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for EFS"
    track_failure "EFS" "$REGION" "Permission denied"
  elif [ $EFS_RC -eq 3 ]; then
    log_warn "[$REGION] EFS not available"
    track_failure "EFS" "$REGION" "Service unavailable"
  fi

  # FSx File Systems
  log_info "[$REGION] Collecting FSx file systems..."
  FSX=$(aws_retry "aws fsx describe-file-systems --region $REGION --query \"FileSystems[].{Id:FileSystemId,Type:FileSystemType,Storage:StorageCapacity}\" --output text" 2>/dev/null)
  FSX_RC=$?
  if [ $FSX_RC -eq 0 ] && [ -n "$FSX" ] && [ "$FSX" != "None" ]; then
    echo "$FSX" | while IFS=$'\t' read -r fsxid fsxstor fsxtype; do
      if [ -n "$fsxid" ]; then
        add_inventory "FSxFileSystem" "$fsxid" "$fsxid" "$REGION" "FSx" "$ACCOUNT_ID" "Type=$fsxtype;Storage=${fsxstor}GB"
      fi
    done
  elif [ $FSX_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for FSx"
    track_failure "FSx" "$REGION" "Permission denied"
  elif [ $FSX_RC -eq 3 ]; then
    log_warn "[$REGION] FSx not available"
    track_failure "FSx" "$REGION" "Service unavailable"
  fi

  # --- Databases ---

  # RDS Instances
  log_info "[$REGION] Collecting RDS instances..."
  RDS=$(aws_retry "aws rds describe-db-instances --region $REGION --query \"DBInstances[].{Id:DBInstanceIdentifier,Engine:Engine,Status:DBInstanceStatus,Class:DBInstanceClass,SubnetGroup:DBSubnetGroup.DBSubnetGroupName,VpcSGs:VpcSecurityGroups[].VpcSecurityGroupId,KmsKeyId:KmsKeyId,Encrypted:StorageEncrypted}\" --output text" 2>/dev/null)
  RDS_RC=$?
  if [ $RDS_RC -eq 0 ] && [ -n "$RDS" ] && [ "$RDS" != "None" ]; then
    RDS_IDS=$(aws_retry "aws rds describe-db-instances --region $REGION --query \"DBInstances[].DBInstanceIdentifier\" --output text" 2>/dev/null)
    RDS_COUNT=0
    # Intentional word splitting: RDS_IDS is a space-delimited list from AWS CLI
    for rdsid in $RDS_IDS; do
      RDS_ENGINE=$(aws_retry "aws rds describe-db-instances --region $REGION --db-instance-identifier \"$rdsid\" --query \"DBInstances[0].Engine\" --output text" 2>/dev/null)
      RDS_CLASS=$(aws_retry "aws rds describe-db-instances --region $REGION --db-instance-identifier \"$rdsid\" --query \"DBInstances[0].DBInstanceClass\" --output text" 2>/dev/null)
      RDS_SUBGRP=$(aws_retry "aws rds describe-db-instances --region $REGION --db-instance-identifier \"$rdsid\" --query \"DBInstances[0].DBSubnetGroup.DBSubnetGroupName\" --output text" 2>/dev/null)
      RDS_SGS=$(aws_retry "aws rds describe-db-instances --region $REGION --db-instance-identifier \"$rdsid\" --query \"DBInstances[0].VpcSecurityGroups[].VpcSecurityGroupId\" --output text" 2>/dev/null)
      RDS_KMS=$(aws_retry "aws rds describe-db-instances --region $REGION --db-instance-identifier \"$rdsid\" --query \"DBInstances[0].KmsKeyId\" --output text" 2>/dev/null)
      RDS_ENC=$(aws_retry "aws rds describe-db-instances --region $REGION --db-instance-identifier \"$rdsid\" --query \"DBInstances[0].StorageEncrypted\" --output text" 2>/dev/null)
      add_inventory "RDSInstance" "$rdsid" "$rdsid" "$REGION" "RDS" "$ACCOUNT_ID" "Engine=$RDS_ENGINE;Class=$RDS_CLASS;Encrypted=$RDS_ENC"
      RDS_COUNT=$((RDS_COUNT + 1))
      # RDS -> Subnet Group dependency
      if [ -n "$RDS_SUBGRP" ] && [ "$RDS_SUBGRP" != "None" ]; then
        add_dependency "$rdsid" "RDS-SubnetGroup" "$RDS_SUBGRP" "$REGION"
      fi
      # RDS -> Security Group dependencies
      if [ -n "$RDS_SGS" ] && [ "$RDS_SGS" != "None" ]; then
        # Intentional word splitting: RDS_SGS is a space-delimited list from AWS CLI
        for rdssg in $RDS_SGS; do
          add_dependency "$rdsid" "RDS-SecurityGroup" "$rdssg" "$REGION"
        done
      fi
      # RDS -> KMS Key dependency
      if [ "$RDS_ENC" = "True" ] && [ -n "$RDS_KMS" ] && [ "$RDS_KMS" != "None" ]; then
        add_dependency "$rdsid" "RDS-KMSKey" "$RDS_KMS" "$REGION"
      fi
    done
    log_ok "[$REGION] Found $RDS_COUNT RDS instances"
  elif [ $RDS_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for RDS"
    track_failure "RDSInstance" "$REGION" "Permission denied"
  elif [ $RDS_RC -eq 3 ]; then
    log_warn "[$REGION] RDS service not available"
    track_failure "RDSInstance" "$REGION" "Service unavailable"
  fi

  # RDS Clusters (Aurora)
  log_info "[$REGION] Collecting RDS/Aurora clusters..."
  CLUSTERS=$(aws_retry "aws rds describe-db-clusters --region $REGION --query \"DBClusters[].{Id:DBClusterIdentifier,Engine:Engine,Status:Status,GlobalClusterId:GlobalClusterIdentifier}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$CLUSTERS" ] && [ "$CLUSTERS" != "None" ]; then
    echo "$CLUSTERS" | while IFS=$'\t' read -r cleng clglobal clid clstatus; do
      if [ -n "$clid" ]; then
        add_inventory "RDSCluster" "$clid" "$clid" "$REGION" "RDS" "$ACCOUNT_ID" "Engine=$cleng;Status=$clstatus"
        # Aurora -> Global Cluster dependency
        if [ -n "$clglobal" ] && [ "$clglobal" != "None" ]; then
          add_dependency "$clid" "Aurora-GlobalCluster" "$clglobal" "$REGION"
        fi
      fi
    done
  fi

  # RDS Snapshots
  log_info "[$REGION] Collecting RDS snapshots..."
  RDS_SNAPS=$(aws_retry "aws rds describe-db-snapshots --region $REGION --query \"DBSnapshots[?DBSnapshotIdentifier!=null].{Id:DBSnapshotIdentifier,DBId:DBInstanceIdentifier,Status:Status,Engine:Engine}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$RDS_SNAPS" ] && [ "$RDS_SNAPS" != "None" ]; then
    echo "$RDS_SNAPS" | while IFS=$'\t' read -r rsdbid rseng rsid rsstatus; do
      if [ -n "$rsid" ]; then
        add_inventory "RDSSnapshot" "$rsid" "$rsid" "$REGION" "RDS" "$ACCOUNT_ID" "DBInstance=$rsdbid;Engine=$rseng"
      fi
    done
  fi

  # Aurora Global Clusters (only in primary region, but collect everywhere to catch)
  GLOBAL_CL=$(aws_retry "aws rds describe-global-clusters --region $REGION --query \"GlobalClusters[].{Id:GlobalClusterIdentifier,Engine:Engine,Status:Status}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$GLOBAL_CL" ] && [ "$GLOBAL_CL" != "None" ]; then
    echo "$GLOBAL_CL" | while IFS=$'\t' read -r gceng gcid gcstatus; do
      if [ -n "$gcid" ]; then
        add_inventory "AuroraGlobalCluster" "$gcid" "$gcid" "$REGION" "RDS" "$ACCOUNT_ID" "Engine=$gceng;Status=$gcstatus"
      fi
    done
  fi

  # DynamoDB Tables
  log_info "[$REGION] Collecting DynamoDB tables..."
  DDB=$(aws_retry "aws dynamodb list-tables --region $REGION --query \"TableNames\" --output text" 2>/dev/null)
  DDB_RC=$?
  if [ $DDB_RC -eq 0 ] && [ -n "$DDB" ] && [ "$DDB" != "None" ]; then
    DDB_COUNT=0
    # Intentional word splitting: DDB is a space-delimited list from AWS CLI
    for tbl in $DDB; do
      TBL_STATUS=$(aws_retry "aws dynamodb describe-table --region $REGION --table-name \"$tbl\" --query \"Table.TableStatus\" --output text" 2>/dev/null)
      TBL_SIZE=$(aws_retry "aws dynamodb describe-table --region $REGION --table-name \"$tbl\" --query \"Table.TableSizeBytes\" --output text" 2>/dev/null)
      add_inventory "DynamoDBTable" "$tbl" "$tbl" "$REGION" "DynamoDB" "$ACCOUNT_ID" "Status=$TBL_STATUS;SizeBytes=$TBL_SIZE"
      DDB_COUNT=$((DDB_COUNT + 1))
    done
    log_ok "[$REGION] Found $DDB_COUNT DynamoDB tables"
  elif [ $DDB_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for DynamoDB"
    track_failure "DynamoDB" "$REGION" "Permission denied"
  elif [ $DDB_RC -eq 3 ]; then
    log_warn "[$REGION] DynamoDB service not available"
    track_failure "DynamoDB" "$REGION" "Service unavailable"
  fi

  # --- Containers ---

  # EKS Clusters
  log_info "[$REGION] Collecting EKS clusters..."
  EKS=$(aws_retry "aws eks list-clusters --region $REGION --query \"clusters\" --output text" 2>/dev/null)
  EKS_RC=$?
  if [ $EKS_RC -eq 0 ] && [ -n "$EKS" ] && [ "$EKS" != "None" ]; then
    # Intentional word splitting: EKS is a space-delimited list from AWS CLI
    for eksname in $EKS; do
      EKS_VPC=$(aws_retry "aws eks describe-cluster --region $REGION --name \"$eksname\" --query \"cluster.resourcesVpcConfig.vpcId\" --output text" 2>/dev/null)
      EKS_SUBNETS=$(aws_retry "aws eks describe-cluster --region $REGION --name \"$eksname\" --query \"cluster.resourcesVpcConfig.subnetIds\" --output text" 2>/dev/null)
      EKS_SGS=$(aws_retry "aws eks describe-cluster --region $REGION --name \"$eksname\" --query \"cluster.resourcesVpcConfig.securityGroupIds\" --output text" 2>/dev/null)
      add_inventory "EKSCluster" "$eksname" "$eksname" "$REGION" "EKS" "$ACCOUNT_ID" "VPC=$EKS_VPC"
      # EKS -> Subnet dependencies
      if [ -n "$EKS_SUBNETS" ] && [ "$EKS_SUBNETS" != "None" ]; then
        # Intentional word splitting: EKS_SUBNETS is a space-delimited list from AWS CLI
        for eksub in $EKS_SUBNETS; do
          add_dependency "$eksname" "EKS-Subnet" "$eksub" "$REGION"
        done
      fi
      # EKS -> Security Group dependencies
      if [ -n "$EKS_SGS" ] && [ "$EKS_SGS" != "None" ]; then
        # Intentional word splitting: EKS_SGS is a space-delimited list from AWS CLI
        for eksg in $EKS_SGS; do
          add_dependency "$eksname" "EKS-SecurityGroup" "$eksg" "$REGION"
        done
      fi
    done
  elif [ $EKS_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for EKS"
    track_failure "EKS" "$REGION" "Permission denied"
  elif [ $EKS_RC -eq 3 ]; then
    log_warn "[$REGION] EKS not available"
    track_failure "EKS" "$REGION" "Service unavailable"
  fi

  # ECS Clusters
  log_info "[$REGION] Collecting ECS clusters..."
  ECS=$(aws_retry "aws ecs list-clusters --region $REGION --query \"clusterArns\" --output text" 2>/dev/null)
  ECS_RC=$?
  if [ $ECS_RC -eq 0 ] && [ -n "$ECS" ] && [ "$ECS" != "None" ]; then
    # Intentional word splitting: ECS is a space-delimited list from AWS CLI
    for ecsarn in $ECS; do
      ECS_NAME=$(aws_retry "aws ecs describe-clusters --region $REGION --clusters \"$ecsarn\" --query \"clusters[0].clusterName\" --output text" 2>/dev/null)
      ECS_STATUS=$(aws_retry "aws ecs describe-clusters --region $REGION --clusters \"$ecsarn\" --query \"clusters[0].status\" --output text" 2>/dev/null)
      add_inventory "ECSCluster" "$ecsarn" "${ECS_NAME:-$ecsarn}" "$REGION" "ECS" "$ACCOUNT_ID" "Status=$ECS_STATUS"
      # ECS services -> subnets, SGs, target groups
      ECS_SVCS=$(aws_retry "aws ecs list-services --region $REGION --cluster \"$ecsarn\" --query \"serviceArns\" --output text" 2>/dev/null)
      if [ $? -eq 0 ] && [ -n "$ECS_SVCS" ] && [ "$ECS_SVCS" != "None" ]; then
        # Intentional word splitting: ECS_SVCS is a space-delimited list from AWS CLI
        for ecssvc in $ECS_SVCS; do
          SVC_SUBNETS=$(aws_retry "aws ecs describe-services --region $REGION --cluster \"$ecsarn\" --services \"$ecssvc\" --query \"services[0].networkConfiguration.awsvpcConfiguration.subnets\" --output text" 2>/dev/null)
          SVC_SGS=$(aws_retry "aws ecs describe-services --region $REGION --cluster \"$ecsarn\" --services \"$ecssvc\" --query \"services[0].networkConfiguration.awsvpcConfiguration.securityGroups\" --output text" 2>/dev/null)
          SVC_TGS=$(aws_retry "aws ecs describe-services --region $REGION --cluster \"$ecsarn\" --services \"$ecssvc\" --query \"services[0].loadBalancers[].targetGroupArn\" --output text" 2>/dev/null)
          if [ -n "$SVC_SUBNETS" ] && [ "$SVC_SUBNETS" != "None" ]; then
            # Intentional word splitting: SVC_SUBNETS is a space-delimited list from AWS CLI
            for ecssub in $SVC_SUBNETS; do
              add_dependency "$ecsarn" "ECS-Subnet" "$ecssub" "$REGION"
            done
          fi
          if [ -n "$SVC_SGS" ] && [ "$SVC_SGS" != "None" ]; then
            # Intentional word splitting: SVC_SGS is a space-delimited list from AWS CLI
            for ecssg in $SVC_SGS; do
              add_dependency "$ecsarn" "ECS-SecurityGroup" "$ecssg" "$REGION"
            done
          fi
          if [ -n "$SVC_TGS" ] && [ "$SVC_TGS" != "None" ]; then
            # Intentional word splitting: SVC_TGS is a space-delimited list from AWS CLI
            for ecstg in $SVC_TGS; do
              add_dependency "$ecsarn" "ECS-TargetGroup" "$ecstg" "$REGION"
            done
          fi
        done
      fi
    done
  elif [ $ECS_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for ECS"
    track_failure "ECS" "$REGION" "Permission denied"
  elif [ $ECS_RC -eq 3 ]; then
    log_warn "[$REGION] ECS not available"
    track_failure "ECS" "$REGION" "Service unavailable"
  fi

  # --- Serverless ---

  # Lambda Functions
  log_info "[$REGION] Collecting Lambda functions..."
  LAMBDAS=$(aws_retry "aws lambda list-functions --region $REGION --query \"Functions[].{Name:FunctionName,ARN:FunctionArn,Runtime:Runtime,Role:Role}\" --output text" 2>/dev/null)
  LAMBDA_RC=$?
  if [ $LAMBDA_RC -eq 0 ] && [ -n "$LAMBDAS" ] && [ "$LAMBDAS" != "None" ]; then
    LAMBDA_NAMES=$(aws_retry "aws lambda list-functions --region $REGION --query \"Functions[].FunctionName\" --output text" 2>/dev/null)
    LAMBDA_COUNT=0
    # Intentional word splitting: LAMBDA_NAMES is a space-delimited list from AWS CLI
    for lfn in $LAMBDA_NAMES; do
      LF_RUNTIME=$(aws_retry "aws lambda get-function-configuration --region $REGION --function-name \"$lfn\" --query \"Runtime\" --output text" 2>/dev/null)
      LF_ROLE=$(aws_retry "aws lambda get-function-configuration --region $REGION --function-name \"$lfn\" --query \"Role\" --output text" 2>/dev/null)
      LF_VPC=$(aws_retry "aws lambda get-function-configuration --region $REGION --function-name \"$lfn\" --query \"VpcConfig.VpcId\" --output text" 2>/dev/null)
      LF_SUBNETS=$(aws_retry "aws lambda get-function-configuration --region $REGION --function-name \"$lfn\" --query \"VpcConfig.SubnetIds\" --output text" 2>/dev/null)
      LF_SGS=$(aws_retry "aws lambda get-function-configuration --region $REGION --function-name \"$lfn\" --query \"VpcConfig.SecurityGroupIds\" --output text" 2>/dev/null)
      add_inventory "LambdaFunction" "$lfn" "$lfn" "$REGION" "Lambda" "$ACCOUNT_ID" "Runtime=$LF_RUNTIME"
      LAMBDA_COUNT=$((LAMBDA_COUNT + 1))
      # Lambda -> IAM Role dependency
      if [ -n "$LF_ROLE" ] && [ "$LF_ROLE" != "None" ]; then
        add_dependency "$lfn" "Lambda-IAMRole" "$LF_ROLE" "$REGION"
      fi
      # Lambda -> VPC/Subnet/SG dependencies
      if [ -n "$LF_VPC" ] && [ "$LF_VPC" != "None" ] && [ "$LF_VPC" != "" ]; then
        add_dependency "$lfn" "Lambda-VPC" "$LF_VPC" "$REGION"
        if [ -n "$LF_SUBNETS" ] && [ "$LF_SUBNETS" != "None" ]; then
          # Intentional word splitting: LF_SUBNETS is a space-delimited list from AWS CLI
          for lsub in $LF_SUBNETS; do
            add_dependency "$lfn" "Lambda-Subnet" "$lsub" "$REGION"
          done
        fi
        if [ -n "$LF_SGS" ] && [ "$LF_SGS" != "None" ]; then
          # Intentional word splitting: LF_SGS is a space-delimited list from AWS CLI
          for lsg in $LF_SGS; do
            add_dependency "$lfn" "Lambda-SecurityGroup" "$lsg" "$REGION"
          done
        fi
      fi
    done
    log_ok "[$REGION] Found $LAMBDA_COUNT Lambda functions"
  elif [ $LAMBDA_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for Lambda"
    track_failure "Lambda" "$REGION" "Permission denied"
  elif [ $LAMBDA_RC -eq 3 ]; then
    log_warn "[$REGION] Lambda service not available"
    track_failure "Lambda" "$REGION" "Service unavailable"
  fi

  # --- Integration Services ---

  # SQS Queues
  log_info "[$REGION] Collecting SQS queues..."
  SQS=$(aws_retry "aws sqs list-queues --region $REGION --query \"QueueUrls\" --output text" 2>/dev/null)
  SQS_RC=$?
  if [ $SQS_RC -eq 0 ] && [ -n "$SQS" ] && [ "$SQS" != "None" ]; then
    # Intentional word splitting: SQS is a space-delimited list from AWS CLI
    for sqsurl in $SQS; do
      SQS_NAME=$(echo "$sqsurl" | awk -F/ '{print $NF}')
      add_inventory "SQSQueue" "$sqsurl" "$SQS_NAME" "$REGION" "SQS" "$ACCOUNT_ID" ""
    done
  elif [ $SQS_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for SQS"
    track_failure "SQS" "$REGION" "Permission denied"
  elif [ $SQS_RC -eq 3 ]; then
    log_warn "[$REGION] SQS not available"
    track_failure "SQS" "$REGION" "Service unavailable"
  fi

  # SNS Topics
  log_info "[$REGION] Collecting SNS topics..."
  SNS=$(aws_retry "aws sns list-topics --region $REGION --query \"Topics[].TopicArn\" --output text" 2>/dev/null)
  SNS_RC=$?
  if [ $SNS_RC -eq 0 ] && [ -n "$SNS" ] && [ "$SNS" != "None" ]; then
    # Intentional word splitting: SNS is a space-delimited list from AWS CLI
    for snsarn in $SNS; do
      SNS_NAME=$(echo "$snsarn" | awk -F: '{print $NF}')
      add_inventory "SNSTopic" "$snsarn" "$SNS_NAME" "$REGION" "SNS" "$ACCOUNT_ID" ""
    done
  elif [ $SNS_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for SNS"
    track_failure "SNS" "$REGION" "Permission denied"
  elif [ $SNS_RC -eq 3 ]; then
    log_warn "[$REGION] SNS not available"
    track_failure "SNS" "$REGION" "Service unavailable"
  fi

  # EventBridge Rules
  log_info "[$REGION] Collecting EventBridge rules..."
  EB_RULES=$(aws_retry "aws events list-rules --region $REGION --query \"Rules[].{Name:Name,Arn:Arn,State:State}\" --output text" 2>/dev/null)
  EB_RC=$?
  if [ $EB_RC -eq 0 ] && [ -n "$EB_RULES" ] && [ "$EB_RULES" != "None" ]; then
    echo "$EB_RULES" | while IFS=$'\t' read -r ebarn ebname ebstate; do
      if [ -n "$ebname" ]; then
        add_inventory "EventBridgeRule" "$ebarn" "$ebname" "$REGION" "EventBridge" "$ACCOUNT_ID" "State=$ebstate"
      fi
    done
  elif [ $EB_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for EventBridge"
    track_failure "EventBridge" "$REGION" "Permission denied"
  elif [ $EB_RC -eq 3 ]; then
    log_warn "[$REGION] EventBridge not available"
    track_failure "EventBridge" "$REGION" "Service unavailable"
  fi

  # --- Backup/DR ---

  # AWS Backup Vaults
  log_info "[$REGION] Collecting AWS Backup vaults..."
  BK_VAULTS=$(aws_retry "aws backup list-backup-vaults --region $REGION --query \"BackupVaultList[].{Name:BackupVaultName,ARN:BackupVaultArn}\" --output text" 2>/dev/null)
  BK_RC=$?
  if [ $BK_RC -eq 0 ] && [ -n "$BK_VAULTS" ] && [ "$BK_VAULTS" != "None" ]; then
    echo "$BK_VAULTS" | while IFS=$'\t' read -r bkvarn bkvname; do
      if [ -n "$bkvname" ]; then
        add_inventory "BackupVault" "$bkvarn" "$bkvname" "$REGION" "Backup" "$ACCOUNT_ID" ""
        # Recovery Points in this vault
        RP=$(aws_retry "aws backup list-recovery-points-by-backup-vault --region $REGION --backup-vault-name \"$bkvname\" --query \"RecoveryPoints[].{ARN:RecoveryPointArn,ResourceARN:ResourceArn,Status:Status}\" --output text" 2>/dev/null)
        if [ $? -eq 0 ] && [ -n "$RP" ] && [ "$RP" != "None" ]; then
          echo "$RP" | while IFS=$'\t' read -r rparn rpresource rpstatus; do
            if [ -n "$rparn" ]; then
              add_inventory "BackupRecoveryPoint" "$rparn" "$rparn" "$REGION" "Backup" "$ACCOUNT_ID" "Status=$rpstatus;Source=$rpresource"
              add_dependency "$bkvarn" "BackupVault-RecoveryPoint" "$rparn" "$REGION"
              if [ -n "$rpresource" ] && [ "$rpresource" != "None" ]; then
                add_dependency "$rparn" "RecoveryPoint-SourceResource" "$rpresource" "$REGION"
              fi
            fi
          done
        fi
      fi
    done
  elif [ $BK_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for AWS Backup"
    track_failure "Backup" "$REGION" "Permission denied"
  elif [ $BK_RC -eq 3 ]; then
    log_warn "[$REGION] AWS Backup not available"
    track_failure "Backup" "$REGION" "Service unavailable"
  fi

  # AWS Backup Plans
  log_info "[$REGION] Collecting AWS Backup plans..."
  BK_PLANS=$(aws_retry "aws backup list-backup-plans --region $REGION --query \"BackupPlansList[].{Id:BackupPlanId,Name:BackupPlanName,ARN:BackupPlanArn}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$BK_PLANS" ] && [ "$BK_PLANS" != "None" ]; then
    echo "$BK_PLANS" | while IFS=$'\t' read -r bkparn bkpid bkpname; do
      if [ -n "$bkpid" ]; then
        add_inventory "BackupPlan" "$bkparn" "$bkpname" "$REGION" "Backup" "$ACCOUNT_ID" ""
      fi
    done
  fi

  # --- Data Migration (DMS) ---

  # DMS Replication Instances
  log_info "[$REGION] Collecting DMS replication instances..."
  DMS_RI=$(aws_retry "aws dms describe-replication-instances --region $REGION --query \"ReplicationInstances[].{Id:ReplicationInstanceIdentifier,ARN:ReplicationInstanceArn,Class:ReplicationInstanceClass,Status:ReplicationInstanceStatus}\" --output text" 2>/dev/null)
  DMS_RC=$?
  if [ $DMS_RC -eq 0 ] && [ -n "$DMS_RI" ] && [ "$DMS_RI" != "None" ]; then
    echo "$DMS_RI" | while IFS=$'\t' read -r dmsarn dmsclass dmsid dmsstatus; do
      if [ -n "$dmsid" ]; then
        add_inventory "DMSReplicationInstance" "$dmsarn" "$dmsid" "$REGION" "DMS" "$ACCOUNT_ID" "Class=$dmsclass;Status=$dmsstatus"
      fi
    done
  elif [ $DMS_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for DMS"
    track_failure "DMS" "$REGION" "Permission denied"
  elif [ $DMS_RC -eq 3 ]; then
    log_warn "[$REGION] DMS not available"
    track_failure "DMS" "$REGION" "Service unavailable"
  fi

  # DMS Replication Tasks
  log_info "[$REGION] Collecting DMS replication tasks..."
  DMS_TASKS=$(aws_retry "aws dms describe-replication-tasks --region $REGION --query \"ReplicationTasks[].{Id:ReplicationTaskIdentifier,ARN:ReplicationTaskArn,SourceEP:SourceEndpointArn,TargetEP:TargetEndpointArn,ReplInstARN:ReplicationInstanceArn,Status:Status}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$DMS_TASKS" ] && [ "$DMS_TASKS" != "None" ]; then
    echo "$DMS_TASKS" | while IFS=$'\t' read -r dtarn dtid dtreplarn dtsrcarn dtstatus dttgtarn; do
      if [ -n "$dtid" ]; then
        add_inventory "DMSReplicationTask" "$dtarn" "$dtid" "$REGION" "DMS" "$ACCOUNT_ID" "Status=$dtstatus"
        # DMS Task -> Source Endpoint
        if [ -n "$dtsrcarn" ] && [ "$dtsrcarn" != "None" ]; then
          add_dependency "$dtarn" "DMSTask-SourceEndpoint" "$dtsrcarn" "$REGION"
        fi
        # DMS Task -> Target Endpoint
        if [ -n "$dttgtarn" ] && [ "$dttgtarn" != "None" ]; then
          add_dependency "$dtarn" "DMSTask-TargetEndpoint" "$dttgtarn" "$REGION"
        fi
        # DMS Task -> Replication Instance
        if [ -n "$dtreplarn" ] && [ "$dtreplarn" != "None" ]; then
          add_dependency "$dtarn" "DMSTask-ReplicationInstance" "$dtreplarn" "$REGION"
        fi
      fi
    done
  fi

  # DMS Endpoints (source and target)
  log_info "[$REGION] Collecting DMS endpoints..."
  DMS_EP=$(aws_retry "aws dms describe-endpoints --region $REGION --query \"Endpoints[].{Id:EndpointIdentifier,ARN:EndpointArn,Type:EndpointType,Engine:EngineName}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$DMS_EP" ] && [ "$DMS_EP" != "None" ]; then
    echo "$DMS_EP" | while IFS=$'\t' read -r eparn epeng epid eptype; do
      if [ -n "$epid" ]; then
        add_inventory "DMSEndpoint" "$eparn" "$epid" "$REGION" "DMS" "$ACCOUNT_ID" "Type=$eptype;Engine=$epeng"
      fi
    done
  fi

  # --- Security/Encryption ---

  # KMS Keys
  log_info "[$REGION] Collecting KMS keys..."
  KMS_KEYS=$(aws_retry "aws kms list-keys --region $REGION --query \"Keys[].KeyId\" --output text" 2>/dev/null)
  KMS_RC=$?
  if [ $KMS_RC -eq 0 ] && [ -n "$KMS_KEYS" ] && [ "$KMS_KEYS" != "None" ]; then
    # Intentional word splitting: KMS_KEYS is a space-delimited list from AWS CLI
    for kmsid in $KMS_KEYS; do
      KMS_DESC=$(aws_retry "aws kms describe-key --region $REGION --key-id \"$kmsid\" --query \"KeyMetadata.{State:KeyState,Manager:KeyManager,Desc:Description}\" --output text" 2>/dev/null)
      KMS_STATE=$(echo "$KMS_DESC" | awk '{print $1}')
      KMS_MGR=$(echo "$KMS_DESC" | awk '{print $2}')
      if [ "$KMS_MGR" = "CUSTOMER" ]; then
        add_inventory "KMSKey" "$kmsid" "$kmsid" "$REGION" "KMS" "$ACCOUNT_ID" "State=$KMS_STATE;Manager=$KMS_MGR"
      fi
    done
  elif [ $KMS_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for KMS"
    track_failure "KMS" "$REGION" "Permission denied"
  elif [ $KMS_RC -eq 3 ]; then
    log_warn "[$REGION] KMS service not available"
    track_failure "KMS" "$REGION" "Service unavailable"
  fi

  # ACM Certificates
  log_info "[$REGION] Collecting ACM certificates..."
  ACM=$(aws_retry "aws acm list-certificates --region $REGION --query \"CertificateSummaryList[].{ARN:CertificateArn,Domain:DomainName,Status:Status}\" --output text" 2>/dev/null)
  ACM_RC=$?
  if [ $ACM_RC -eq 0 ] && [ -n "$ACM" ] && [ "$ACM" != "None" ]; then
    echo "$ACM" | while IFS=$'\t' read -r acmarn acmdomain acmstatus; do
      if [ -n "$acmarn" ]; then
        add_inventory "ACMCertificate" "$acmarn" "$acmdomain" "$REGION" "ACM" "$ACCOUNT_ID" "Status=$acmstatus"
      fi
    done
  elif [ $ACM_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for ACM"
    track_failure "ACM" "$REGION" "Permission denied"
  elif [ $ACM_RC -eq 3 ]; then
    log_warn "[$REGION] ACM not available"
    track_failure "ACM" "$REGION" "Service unavailable"
  fi

  # SSM Parameter Store (metadata only)
  log_info "[$REGION] Collecting SSM parameters (metadata)..."
  SSM_PARAMS=$(aws_retry "aws ssm describe-parameters --region $REGION --query \"Parameters[].{Name:Name,Type:Type,LastModified:LastModifiedDate}\" --output text" 2>/dev/null)
  SSM_RC=$?
  if [ $SSM_RC -eq 0 ] && [ -n "$SSM_PARAMS" ] && [ "$SSM_PARAMS" != "None" ]; then
    echo "$SSM_PARAMS" | while IFS=$'\t' read -r ssmlm ssmname ssmtype; do
      if [ -n "$ssmname" ]; then
        add_inventory "SSMParameter" "$ssmname" "$ssmname" "$REGION" "SSM" "$ACCOUNT_ID" "Type=$ssmtype"
      fi
    done
  elif [ $SSM_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for SSM"
    track_failure "SSMParameter" "$REGION" "Permission denied"
  elif [ $SSM_RC -eq 3 ]; then
    log_warn "[$REGION] SSM service not available"
    track_failure "SSMParameter" "$REGION" "Service unavailable"
  fi

  # Secrets Manager (metadata only)
  log_info "[$REGION] Collecting Secrets Manager secrets (metadata)..."
  SECRETS=$(aws_retry "aws secretsmanager list-secrets --region $REGION --query \"SecretList[].{Name:Name,ARN:ARN,LastChanged:LastChangedDate}\" --output text" 2>/dev/null)
  SEC_RC=$?
  if [ $SEC_RC -eq 0 ] && [ -n "$SECRETS" ] && [ "$SECRETS" != "None" ]; then
    echo "$SECRETS" | while IFS=$'\t' read -r secarn seclc secname; do
      if [ -n "$secname" ]; then
        add_inventory "Secret" "$secarn" "$secname" "$REGION" "SecretsManager" "$ACCOUNT_ID" ""
      fi
    done
  elif [ $SEC_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for Secrets Manager"
    track_failure "SecretsManager" "$REGION" "Permission denied"
  elif [ $SEC_RC -eq 3 ]; then
    log_warn "[$REGION] Secrets Manager not available"
    track_failure "SecretsManager" "$REGION" "Service unavailable"
  fi

  # --- Monitoring ---

  # CloudWatch Alarms
  log_info "[$REGION] Collecting CloudWatch alarms..."
  CW_ALARMS=$(aws_retry "aws cloudwatch describe-alarms --region $REGION --query \"MetricAlarms[].{Name:AlarmName,ARN:AlarmArn,State:StateValue}\" --output text" 2>/dev/null)
  CW_RC=$?
  if [ $CW_RC -eq 0 ] && [ -n "$CW_ALARMS" ] && [ "$CW_ALARMS" != "None" ]; then
    echo "$CW_ALARMS" | while IFS=$'\t' read -r cwarn cwname cwstate; do
      if [ -n "$cwname" ]; then
        add_inventory "CloudWatchAlarm" "$cwarn" "$cwname" "$REGION" "CloudWatch" "$ACCOUNT_ID" "State=$cwstate"
      fi
    done
  elif [ $CW_RC -eq 2 ]; then
    log_warn "[$REGION] Permission denied for CloudWatch"
    track_failure "CloudWatch" "$REGION" "Permission denied"
  elif [ $CW_RC -eq 3 ]; then
    log_warn "[$REGION] CloudWatch service not available"
    track_failure "CloudWatch" "$REGION" "Service unavailable"
  fi

  # CloudWatch Log Groups
  log_info "[$REGION] Collecting CloudWatch Log Groups..."
  CW_LOGS=$(aws_retry "aws logs describe-log-groups --region $REGION --query \"logGroups[].{Name:logGroupName,ARN:arn,Retention:retentionInDays}\" --output text" 2>/dev/null)
  if [ $? -eq 0 ] && [ -n "$CW_LOGS" ] && [ "$CW_LOGS" != "None" ]; then
    echo "$CW_LOGS" | while IFS=$'\t' read -r lgarn lgname lgret; do
      if [ -n "$lgname" ]; then
        add_inventory "CloudWatchLogGroup" "$lgarn" "$lgname" "$REGION" "CloudWatch" "$ACCOUNT_ID" "Retention=$lgret"
      fi
    done
  fi

  # --- Region elapsed time ---
  REGION_END=$(date +%s)
  REGION_ELAPSED=$((REGION_END - REGION_START))
  log_ok "[$REGION] Region scan complete in ${REGION_ELAPSED}s"
  REGIONS_SCANNED=$((REGIONS_SCANNED + 1))

done

# ============================================================
# COMPLETION SUMMARY
# ============================================================
SCRIPT_END=$(date +%s)
TOTAL_ELAPSED=$((SCRIPT_END - SCRIPT_START))

echo ""
echo "============================================================"
echo "  RMA Environment Discovery — Summary"
echo "============================================================"
echo "  Account ID:         $ACCOUNT_ID"
echo "  Regions scanned:    $REGIONS_SCANNED"
echo "  Total resources:    $TOTAL_RESOURCES"
echo "  Total dependencies: $TOTAL_DEPENDENCIES"
echo "  Total runtime:      ${TOTAL_ELAPSED}s"
echo "  Inventory file:     $INVENTORY_FILE"
echo "  Dependency file:    $DEPENDENCY_FILE"
echo "============================================================"

if [ -n "$COLLECTION_FAILURES" ]; then
  echo ""
  log_warn "WARNING: Output is incomplete. The following resource types or regions could not be fully collected:"
  echo -e "$COLLECTION_FAILURES"
  echo "# COLLECTION_STATUS: INCOMPLETE — see terminal output for details" >> "$INVENTORY_FILE"
  echo "# COLLECTION_STATUS: INCOMPLETE — see terminal output for details" >> "$DEPENDENCY_FILE"
else
  log_ok "COLLECTION STATUS: COMPLETE"
fi

log_ok "Discovery complete. Review the CSV files for your infrastructure inventory."
